name: assimp

on:
  push:
    paths:
      - .github/workflows/assimp.yml
      - assimp/**
  workflow_dispatch:

jobs:
  ci:
    permissions:
      contents: write
    uses: ./.github/workflows/_build.yml
    with: { lib: assimp, version: v1.0 }
    secrets: inherit
