name: pugixml
# 008

on:
  push:
    paths:
      - pugixml/**
      - .github/workflows/pugixml.yml
  workflow_dispatch:
    
jobs:
  ci:
    permissions:
      contents: write

    uses: ./.github/workflows/_build.yml
    with: {
        lib: pugixml,
        version: v1.0,
        # multistrap: true,
        linux_apt: libx11-dev libglu1-mesa-dev libgl1-mesa-dev libwayland-dev libxkbcommon-dev xorg-dev libegl1-mesa-dev libopengl-dev libglx-dev libglvnd-dev,
      }
    secrets: inherit
